# Generated by Django 5.2.17 on 2026-09-18 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('parent_name', models.CharField(max_length=150)),
                ('parent_contact', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Pending', 'Application Submitted'), ('Parent Verification', 'Parent Verification'), ('Warden Review', 'Warden Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending Verification'), ('Verified', 'Parent Verified'), ('Failed', 'Verification Failed')], default='Pending', max_length=30)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('reviewer_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_outpasses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpasses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
