import React,{useEffect,useRef,useState} from 'react';
import {Link,NavLink,useLocation,useNavigate} from 'react-router-dom';
import {Bell,User,Settings,LogOut,Menu,X,PlusCircle,FileCheck2,Home,Users,MessageSquare,BarChart3,Send,ChevronDown,LayoutDashboard, ClipboardList} from 'lucide-react';
import BrandLogo from './BrandLogo';
import {useAuth} from '../context/AuthContext';
import {useNotifications} from '../context/NotificationContext';

const publicLinks=[['Roles','#roles'],['Why Us','#why-us'],['How It Works','#how-it-works'],['Services','#services'],['FAQs','#faq']];

export default function Navbar(){
 const {user,isAuthenticated,logout,isStudent,isWarden,isAdmin}=useAuth();
 const {unreadCount,setIsDrawerOpen}=useNotifications();
 const [profileOpen,setProfileOpen]=useState(false); const [mobileOpen,setMobileOpen]=useState(false); const ref=useRef(null); const navigate=useNavigate(); const location=useLocation();
 useEffect(()=>{const f=e=>{if(ref.current&&!ref.current.contains(e.target))setProfileOpen(false)};document.addEventListener('mousedown',f);return()=>document.removeEventListener('mousedown',f)},[]);
 useEffect(()=>{setMobileOpen(false);setProfileOpen(false)},[location.pathname]);
 useEffect(()=>{document.body.style.overflow=mobileOpen?'hidden':'';return()=>{document.body.style.overflow=''}},[mobileOpen]);
 const goHome=()=>{setMobileOpen(false);navigate('/')};
 const handleLogout=async()=>{await logout();navigate('/login')};
 const links=isStudent?[['Overview','/student',Home],['Complaints','/complaints',MessageSquare],['Outpasses','/outpasses',FileCheck2]]:isWarden?[['Overview','/warden',LayoutDashboard],['Outpass Desk','/warden/outpasses',ClipboardList],['Students','/warden/students',Users]]:isAdmin?[['Overview','/admin',LayoutDashboard],['Complaints','/admin/complaints',MessageSquare],['Outpasses','/admin/outpasses',FileCheck2],['Students','/admin/students',Users],['Reports','/admin/reports',BarChart3],['Broadcast','/admin/broadcast',Send]]:[];
 const nav=links.map(([label,to,Icon])=><NavLink key={to} to={to} end={to==='/student'||to==='/warden'||to==='/admin'} className={({isActive})=>`group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition-all ${isActive?'bg-[#6B4A35] text-white shadow-sm':'text-[#E7D8C5]/75 hover:bg-white/8 hover:text-white'}`}><Icon className="w-[17px]"/><span>{label}</span></NavLink>);
 if(!isAuthenticated) return <header className="sticky top-0 z-50 border-b border-[#D8CBB9] bg-[#FAF7F1]/95 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1400px] items-center justify-between px-5 sm:px-8"><BrandLogo/><nav className="hidden lg:flex items-center gap-1">{publicLinks.map(([label,href])=><button key={href} onClick={()=>{if(location.pathname!=='/')navigate('/'+href);else document.querySelector(href)?.scrollIntoView({behavior:'smooth'})}} className="rounded-lg px-3 py-2 text-sm font-semibold text-[#6B5B4E] hover:bg-[#EDE0D0] hover:text-[#6B4A35]">{label}</button>)}</nav><div className="hidden sm:flex items-center gap-2"><Link to="/login" className="rounded-xl px-4 py-2 text-sm font-semibold text-[#6B4A35] hover:bg-[#EDE0D0]">Login</Link><Link to="/register" className="rounded-xl bg-[#6B4A35] px-4 py-2 text-sm font-bold text-white shadow-sm hover:bg-[#5B3D2C]">Create account</Link></div><button className="lg:hidden rounded-xl p-2 text-[#6B4A35]" onClick={()=>setMobileOpen(true)}><Menu/></button></div>{mobileOpen&&<div className="fixed inset-0 z-[70] bg-[#2B211B]/50 lg:hidden"><div className="ml-auto h-full w-[min(88vw,360px)] bg-[#FAF7F1] p-5 shadow-2xl"><div className="flex items-center justify-between mb-7"><BrandLogo/><button onClick={()=>setMobileOpen(false)}><X/></button></div><div className="space-y-2">{publicLinks.map(([label,href])=><button key={href} onClick={()=>{setMobileOpen(false);if(location.pathname!=='/')navigate('/'+href);else document.querySelector(href)?.scrollIntoView({behavior:'smooth'})}} className="block w-full rounded-xl p-3 text-left font-semibold text-[#5B3D2C] hover:bg-[#EDE0D0]">{label}</button>)}</div><div className="mt-8 grid gap-2"><Link to="/login" className="rounded-xl border border-[#D8CBB9] p-3 text-center font-semibold">Login</Link><Link to="/register" className="rounded-xl bg-[#6B4A35] p-3 text-center font-bold text-white">Create account</Link></div></div></div>}</header>;
 return <>
  <aside className="fixed inset-y-0 left-0 z-50 hidden w-[260px] flex-col border-r border-[#5B4030] bg-[#2B211B] md:flex">
   <div className="flex h-[72px] items-center border-b border-white/10 px-5"><BrandLogo light/></div>
   <div className="flex-1 overflow-y-auto px-4 py-6"><p className="mb-3 px-2 text-[10px] font-extrabold uppercase tracking-[.18em] text-[#B89B7A]">Workspace</p><nav className="space-y-1">{nav}</nav></div>
   <div className="border-t border-white/10 p-4 space-y-2">
    <button onClick={()=>setIsDrawerOpen(true)} className="relative flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-[#E7D8C5]/75 hover:bg-white/8 hover:text-white"><Bell className="w-[17px]"/>Notifications>{unreadCount>0&&<span className="ml-auto rounded-full bg-[#B58A4A] px-1.5 py-0.5 text-[9px] font-black text-[#2B211B]">{unreadCount>9?'9+':unreadCount}</span>}</button>
    <Link to="/settings" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-[#E7D8C5]/75 hover:bg-white/8 hover:text-white"><Settings className="w-[17px]"/>Settings</Link>
    <div className="relative" ref={ref}><button onClick={()=>setProfileOpen(!profileOpen)} className="flex w-full items-center gap-3 rounded-xl bg-white/5 p-2.5 text-left hover:bg-white/10"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[#6B4A35] font-bold text-[#F3EBDD]">{user?.first_name?.[0]?.toUpperCase()||user?.username?.[0]?.toUpperCase()||'U'}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-white">{user?.first_name?`${user.first_name} ${user.last_name||''}`:user?.username}</p><p className="text-[9px] font-bold uppercase tracking-wider text-[#B89B7A]">{user?.role}</p></div><ChevronDown className="w-4 text-[#B89B7A]"/></button>{profileOpen&&<div className="absolute bottom-[calc(100%+8px)] left-0 right-0 overflow-hidden rounded-xl border border-[#D8CBB9] bg-[#FAF7F1] shadow-2xl"><div className="p-3 border-b border-[#D8CBB9]"><p className="text-xs font-bold text-[#3A2A20]">{user?.email||user?.username}</p></div>{isStudent&&<Link to="/profile" className="flex items-center gap-2 px-3 py-2.5 text-xs font-semibold hover:bg-[#EDE0D0]"><User className="w-4"/>My Profile</Link>}<button onClick={handleLogout} className="flex w-full items-center gap-2 px-3 py-2.5 text-xs font-semibold text-[#7A563D] hover:bg-[#EDE0D0]"><LogOut className="w-4"/>Sign out</button></div>}</div>
   </div>
  </aside>
  <header className="sticky top-0 z-40 flex h-[72px] items-center border-b border-[#D8CBB9] bg-[#FAF7F1]/95 px-4 backdrop-blur-xl md:hidden"><BrandLogo/><div className="ml-auto flex items-center gap-1"><button onClick={()=>setIsDrawerOpen(true)} className="relative rounded-xl p-2 text-[#6B4A35]"><Bell className="w-5"/>{unreadCount>0&&<span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-[#B58A4A]"/>}</button><button onClick={()=>setMobileOpen(true)} className="rounded-xl p-2 text-[#6B4A35]"><Menu/></button></div></header>
  {mobileOpen&&<div className="fixed inset-0 z-[70] bg-[#2B211B]/55 md:hidden"><div className="h-full w-[min(88vw,360px)] bg-[#2B211B] p-4"><div className="mb-7 flex items-center justify-between"><BrandLogo light/><button onClick={()=>setMobileOpen(false)} className="text-[#E7D8C5]"><X/></button></div><nav className="space-y-1">{nav}</nav><div className="mt-6 border-t border-white/10 pt-4"><button onClick={()=>setIsDrawerOpen(true)} className="flex w-full items-center gap-3 rounded-xl p-3 text-sm font-semibold text-[#E7D8C5]"><Bell className="w-4"/>Notifications</button><Link to="/settings" className="flex items-center gap-3 rounded-xl p-3 text-sm font-semibold text-[#E7D8C5]"><Settings className="w-4"/>Settings</Link><button onClick={handleLogout} className="flex w-full items-center gap-3 rounded-xl p-3 text-sm font-semibold text-[#E7D8C5]"><LogOut className="w-4"/>Sign out</button></div></div></div>}
 </>;
}
